server:
  port: 8000
  error:
    # include-exception: false
    # include-stacktrace: never
    include-exception: true
    include-stacktrace: always
    path: /error
    whitelabel:
      enabled: false

spring:
  application:
    name: community-app

  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/20_community_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dreamy

mybatis:
  type-aliases-package: app.community.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    lazy-load-trigger-methods: ''
  type-handlers-package: app.community.mapper.handler